name: hordvoice
description: "HordVoice - Assistant vocal intelligent avec contrôle inter-applications"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # PACKAGES CORE - Versions stables et testées
  flutter_riverpod: 2.6.1
  provider: ^6.1.2
  permission_handler: ^11.3.1
  google_fonts: 6.3.0
  device_info_plus: ^11.0.0
  logger: ^2.6.1
  intl: 0.20.2
  http: 1.5.0
  shared_preferences: 2.5.3
  path_provider: ^2.1.5
  url_launcher: 6.3.2
  flutter_localizations:
    sdk: flutter

  # VOIX  Reconnaissance et synthèse COMPLÈTE
  azure_speech_recognition_flutter: ^1.0.2 # Azure Speech Recognition
  avatar_glow: 2.0.2 # Animation microphone
  flutter_tts: 3.8.5 # Synthèse vocale (version stable)
  flutter_secure_storage: ^9.2.2 # Stockage sécurisé profil vocal
  just_audio: ^0.9.40 # Gestion audio avancée
  audio_session: ^0.1.21 # Configuration session audio

  # LOCATION - Version compatible
  location: ^8.0.1
  geolocator: 10.1.0
  geocoding: ^3.0.0

  # STOCKAGE - Base de données
  hive: 2.2.3
  hive_flutter: 1.1.0
  supabase_flutter: 2.9.1

  # SPOTIFY INTEGRATION - Contrôle musical complet
  crypto: ^3.0.5 # Pour l'authentification OAuth2

  # CALENDRIER
  device_calendar: 4.3.3
  timezone: 0.9.2

  # BACKGROUND TASK - Compatible avec Azure Speech
  flutter_background_service: 5.1.0

  # GOOGLE FIT INTEGRATION
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0

  # ANALYTICS & CHARTS - Pour le tableau de bord
  fl_chart: ^0.70.0
  share_plus: ^10.1.2

  # NAVIGATION AVANCÉE
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  # AUDIO AVANCÉ - Packages compatibles Android 14+
  audioplayers: ^6.1.0
  audio_waveforms: ^1.1.6 # Alternative moderne à record
  # mic_stream: ^0.6.0                  # DÉSACTIVÉ temporairement
  # record: ^5.0.4                    # DÉSACTIVÉ temporairement
  google_sign_in: ^6.2.1

  # CAMÉRA & ANALYSE ÉMOTIONNELLE - Nouveaux packages
  camera: ^0.10.5+9 # Accès caméra pour analyse faciale
  image: ^4.1.7 # Traitement d'images
  tflite_flutter: ^0.10.4 # TensorFlow Lite pour ML local
  google_mlkit_face_detection: ^0.10.0 # ML Kit détection visages

  # RESPONSIVE DESIGN - Multi-plateforme
  responsive_framework: ^1.5.1
  health: ^13.1.1

  # NEW DEPENDENCIES - Communication et Système (TEMPORAIREMENT SIMPLIFIÉES)
  flutter_app_info: ^3.0.3 # Informations application
  # window_manager: ^0.3.9        # Contrôle fenêtres - DÉSACTIVÉ
  # wallpaper_setter: ^0.0.4     # Changement fond d'écran - DÉSACTIVÉ
  # home_widget: ^0.6.0          # Widget écran d'accueil - DÉSACTIVÉ

  # TÉLÉPHONIE - Via permissions natives Android (sans packages tiers)
  # Les fonctionnalités SMS/Appels seront gérées via platform channels natifs

  # SURVEILLANCE TÉLÉPHONE - Santé et performance
  app_usage: ^4.0.1 # Usage applications
  battery_plus: ^6.2.2 # Informations batterie
  system_info2: ^4.0.0 # Informations système
  flutter_webrtc: ^1.0.0

  # AUTRES UTILITAIRES
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.3.0
  lottie: ^3.1.3
  flutter_animate: ^4.5.0
  webview_flutter: ^4.10.0
  flutter_local_notifications: ^18.0.1
  uuid: ^4.5.1
  package_info_plus: ^8.3.1
  animations: ^2.1.0 # Animations onboarding fluides
  rive: ^0.13.15 # Animations avatar avancées
  flutter_dotenv: ^5.1.0 # Gestion fichiers .env
  mic_stream_recorder: ^1.1.2 # Stream audio microphone (package maintenu)
  permission_handler_platform_interface: ^4.2.3 # Interface permissions
  wakelock_plus: ^1.2.8 # Wake lock pour écoute continue
  flutter_azure_tts: ^1.0.0

  # PACKAGES MANQUANTS - Ajout pour finalisation voice-only

  flutter_sound: ^9.16.3 # Alternative stable pour l'audio
  path: ^1.9.0 # Gestion paths fichiers
  dio: ^5.7.0 # HTTP client avancé pour APIs
  cached_network_image: ^3.4.1 # Cache images (logos/assets)
  vibration: ^2.0.0 # Feedback haptique
  screen_brightness: ^1.0.1 # Contrôle luminosité
  volume_controller: ^2.0.7 # Contrôle volume système
  network_info_plus: ^7.0.0 # Info réseau pour diagnostics
  connectivity_plus: ^6.1.0 # État connectivité
  app_settings: ^5.1.1 # Navigation paramètres système

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # Configuration icônes

  # Test dependencies for comprehensive unit testing
  mockito: ^5.4.4 # Mock objects for testing
  build_runner: ^2.4.9 # Code generation for mocks
  test: ^1.25.8 # Additional testing utilities
  fake_async: ^1.3.1 # Testing async code
  clock: ^1.1.1 # Mock time for testing
  http_mock_adapter: ^0.6.1 # Mock HTTP requests

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/hordVoice.png"
  min_sdk_android: 26
  web:
    generate: true
  windows:
    generate: true
    image_path: "assets/images/hordVoice.png"
    icon_size: 48

flutter:
  uses-material-design: true

  # Enable generation of localization files (Flutter will generate
  # the `AppLocalizations` class from the ARB files under `lib/l10n`)
  generate: true

  # Assets de l'application
  assets:
    - assets/images/
    - assets/audio/
    - assets/sounds/
    - .env
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
