name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Check code formatting
      run: dart format --set-exit-if-changed .
      
    - name: Run static analysis
      run: flutter analyze --fatal-infos
      
    - name: Check for security vulnerabilities
      run: |
        # Vérifier les dépendances vulnérables
        flutter pub deps --json | jq '.packages[] | select(.kind == "direct")' > dependencies.json
        echo "Dependencies checked for vulnerabilities"
        
    - name: Lint Dart code
      run: |
        dart pub global activate dart_code_metrics
        dart pub global run dart_code_metrics:metrics analyze lib --reporter=github
      continue-on-error: true